repository:
  name: react-video-player
  visibility: public
  has_issues: true
  has_projects: true
  has_wiki: false

# Branch protection rules for main
branches:
  - name: main
    protection:
      required_status_checks:
        strict: false
        contexts: []
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        require_last_push_approval: true
      restrictions: null
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      required_conversation_resolution: true
      lock_branch: false
      allow_fork_syncing: true

# Merge method settings
allow_merge_commit: true
allow_squash_merge: true
allow_rebase_merge: false
delete_branch_on_merge: true